GET http://localhost:3000/api
?user=user& HTTP/1.1
content-type: application/json

{
    "user": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### 
POST http://localhost:3000/api/register HTTP/1.1
content-type: application/json

{
    "user":{
        "name": "sample",
       "last_name":"foo",
     "email":"mail14@lito.com",
    "password":"1234"
    }
}

###
GET  http://localhost:3000/api/me HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwxNEBsaXRvLmNvbSIsImlkIjoiNWNkZTVlYTBhMmY1ZDgyYjU4ZTJkMzNiIiwiZXhwIjoxNTYzMjYxMDg4LCJpYXQiOjE1NTgwNzcwODh9.9crLg0OnX29bX9JC4RnQnfnOoJEhQqpsWzbqgnEc20Y

### good passwod
POST  http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{
    "user":
        {
    "email":"mail3@lito.com",
    "password":"1234"
    }
}

### Bad password
POST  http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{
"user":{    "email":"mail3@lito.com",
    "password":"12345"}
}
