GET http://localhost:3000/api
?user=user& HTTP/1.1
content-type: application/json

{
    "user": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### 
POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
    "user":{
        "name": "TEST",
       "last_name":"TESTT",
     "email":"mail30@lito.com",
    "password":"1234"
    }
}

###
GET  http://localhost:3000/api/me HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlZWY2Nzc3ZGIzYjUzMzg5ODM2YTgxIiwiZXhwIjoxNTY0NzI3MjUwLCJpYXQiOjE1NTk1NDMyNTB9.871OptD0oVSwoQinBMEElbhj6Lsxp_Loic-lcYkUiEg
### good passwod
POST  http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "user":
        {
    "email":"MAIL",
    "password":"abcd"
    }
}

### Bad password
POST  http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
"user":{    
    "email":"mail3@lito.com",
    "password":"12345"}
}

### FORGOT password
POST  http://localhost:3000/api/auth/forgot HTTP/1.1
content-type: application/json

{
    "email":"MAIL"
}


### FORGOT password
PUT  http://localhost:3000/api/auth/restore HTTP/1.1
content-type: application/json

{
    "email":"MAIL",
    "token":"$2a$04$luAimd2kGOBIYVQiuaEbqO",
    "password":"123456"
}


### Add new pet to user 5ce77a7496a2071f0b7d70a7
POST http://localhost:3000/api/users/5ceef6777db3b53389836a81/pets HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlZWY2Nzc3ZGIzYjUzMzg5ODM2YTgxIiwiZXhwIjoxNTY5MTc1NDk2LCJpYXQiOjE1NjM5OTE0OTZ9.UWYoLsimYb7QQcj0cszvbrGj9g8Dd3A7zmS6diG4Qmg

{
    "pet":{
         "species": "dog",
         "sex": "female",
         "age": "young",
         "name": "Gaturro"
    }
}

### Get pets from user 
GET http://localhost:3000/api/users/5ceef6777db3b53389836a81/pets HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlZWY2Nzc3ZGIzYjUzMzg5ODM2YTgxIiwiZXhwIjoxNTY1MjAyODU3LCJpYXQiOjE1NjAwMTg4NTd9.tI-6h_xGFhS-NxFeRCSc1HH1_g0xNmnvKvuPkqJXVbc


### Get pet from user 
GET http://localhost:3000/api/users/5ceef6777db3b53389836a81/pets/5d389ddb20e1dd2b468c9cb7 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlZWY2Nzc3ZGIzYjUzMzg5ODM2YTgxIiwiZXhwIjoxNTY5MTc1NDk2LCJpYXQiOjE1NjM5OTE0OTZ9.UWYoLsimYb7QQcj0cszvbrGj9g8Dd3A7zmS6diG4Qmg


### Add new search to pet
POST http://localhost:3000/api/users/5ce1b137e0137b3802648da1/pets/5ce77a7496a2071f0b7d70a7/search HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlMWIxMzdlMDEzN2IzODAyNjQ4ZGExIiwiZXhwIjoxNTYzODU3MTgyLCJpYXQiOjE1NTg2NzMxODJ9.18k-dgdISclZidbh66arwqYHxK3C_cs4boC6cRfLxPk

{
    "location":{
        "type" : "Point",
        "coordinates" : [
            -122.5,
            37.7
        ]
    },
    "date": "2019-05-01T00:00:00.000Z"
}

### Get pets arrownd me
GET http://localhost:3000/api/lostpets HTTP/1.1
    ?lat=-35.522620524394135
    &long=-58.30532461073403 
content-type: application/json



### delete search from pet
DELETE http://localhost:3000/api/users/5ceef6777db3b53389836a81/pets/5cf5617c5d66df4434c91de2/search HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlZWY2Nzc3ZGIzYjUzMzg5ODM2YTgxIiwiZXhwIjoxNTY0NTU1ODEyLCJpYXQiOjE1NTkzNzE4MTJ9.sDL88rumweDCM-1VkNrZ-Vktgr5OnN5xA7F4A2MfD8A



### Test image avatar
POST  http://localhost:3000/api/me/avatar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlZWY2Nzc3ZGIzYjUzMzg5ODM2YTgxIiwiZXhwIjoxNTY1MjAyODU3LCJpYXQiOjE1NjAwMTg4NTd9.tI-6h_xGFhS-NxFeRCSc1HH1_g0xNmnvKvuPkqJXVbc
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

avatar
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Test image avatar
get  http://localhost:3000/api/me/avatar
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlZWY2Nzc3ZGIzYjUzMzg5ODM2YTgxIiwiZXhwIjoxNTY1MjAyODU3LCJpYXQiOjE1NjAwMTg4NTd9.tI-6h_xGFhS-NxFeRCSc1HH1_g0xNmnvKvuPkqJXVbc

### Test image avatar
DELETE   http://localhost:3000/api/me/avatar
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlZWY2Nzc3ZGIzYjUzMzg5ODM2YTgxIiwiZXhwIjoxNTY1MjAyODU3LCJpYXQiOjE1NjAwMTg4NTd9.tI-6h_xGFhS-NxFeRCSc1HH1_g0xNmnvKvuPkqJXVbc



### Test image pets
POST  http://localhost:3000/api/users/5ceef6777db3b53389836a81/pets/5cf5617c5d66df4434c91de2/pics
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlZWY2Nzc3ZGIzYjUzMzg5ODM2YTgxIiwiZXhwIjoxNTY2MzQxMTI3LCJpYXQiOjE1NjExNTcxMjd9.MrOAYZBGud_GSqBqJNeCEA0kzYs_0xxIsvWJclZ3BCs
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

principal
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="principal"; filename="1.png"
Content-Type: image/png

------WebKitFormBoundary7MA4YWxkTrZu0gW--


### remove pics pics1561313565493
DELETE   http://localhost:3000/api/users/5ceef6777db3b53389836a81/pets/5cf5617c5d66df4434c91de2/pics/pics1561313565493
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWwyNUBsaXRvLmNvbSIsImlkIjoiNWNlZWY2Nzc3ZGIzYjUzMzg5ODM2YTgxIiwiZXhwIjoxNTY1MjAyODU3LCJpYXQiOjE1NjAwMTg4NTd9.tI-6h_xGFhS-NxFeRCSc1HH1_g0xNmnvKvuPkqJXVbc
