@authToken = {{login.response.body.user.token}}
@idUserLoged = {{login.response.body.user._id}}
@mail = "JamesSmith_mascotas@gmail.com"
@idNewPet = {{addNewPetToUser.response.body.$.id}}
@idFirstPetUser = {{logedPets.response.body.$[0]._id}}
@hostName = localhost
@port = 8000
@host = http://{{hostName}}:{{port}}/api

#AUTHENTIFICATION

### Register new user
POST {{host}}/auth/register HTTP/1.1
content-type: application/json

{
    "user":{
        "name": "TEST",
       "last_name":"TESTT",
     "email": {{mail}},
    "password":"1234"
    }
}

### Log in user
# @name login
POST  {{host}}/auth/login HTTP/1.1
content-type: application/json

{
    "user":
        {
    "email":{{mail}},
    "password":"1234"
    }
}

# USER ACTIONS

### Info about loged user
GET  {{host}}/me HTTP/1.1
content-type: application/json
Authorization: {{authToken}}


# ### Bad password
# POST  {{host}}/auth/login HTTP/1.1
# content-type: application/json

# {
# "user":{    
#     "email":"mail3@lito.com",
#     "password":"12345"}
# }

### FORGOT password obtain token
POST  {{host}}/auth/forgot HTTP/1.1
content-type: application/json

{
    "email":{{mail}}
}


### FORGOT password restore
PUT  {{host}}/auth/restore HTTP/1.1
content-type: application/json

{
    "email":{{mail}},
    "token":"$2a$04$luAimd2kGOBIYVQiuaEbqO",
    "password":"123456"
}

### Test image avatar UPLOAD user avatar 
POST  {{host}}/me/avatar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: {{authToken}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

avatar
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Test image avatar OBTAIN user avatar for profile and nav
get  {{host}}/me/avatar
Authorization: {{authToken}}

### Test image avatar REMOVE user avatar
DELETE   {{host}}/me/avatar
Authorization: {{authToken}}


#PET ACTIONS USER

### Add new pet to user loged

# @name addNewPetToUser
POST {{host}}/users/{{idUserLoged}}/pets HTTP/1.1
content-type: application/json
Authorization: {{authToken}}

{
    "pet":{
         "species": "cat",
         "sex": "female",
         "age": "old",
         "name": "Cachito"
    }
}

### Get pets from user 
## ademas agrega a la variable idFirstPetUser la primer mascota, par utilizar en otra funciones
# @name logedPets
GET {{host}}/users/{{idUserLoged}}/pets HTTP/1.1
content-type: application/json
Authorization: {{authToken}}


### Get pet from user 
GET {{host}}/users/{{idUserLoged}}/pets/{{idFirstPetUser}} HTTP/1.1
content-type: application/json
Authorization: {{authToken}}

### Add new search to pet
POST {{host}}/users/{{idUserLoged}}/pets/{{idFirstPetUser}}/search HTTP/1.1
content-type: application/json
Authorization: {{authToken}}

{
    "location":{
        "type" : "Point",
        "coordinates" : [
            -35.51713,
            -58.31567
        ]
    },
    "date": "2019-05-01T00:00:00.000Z"
}

### Get search id from user 
GET {{host}}/users/{{idUserLoged}}/pets/{{idNewPet}}/search HTTP/1.1
content-type: application/json
Authorization: {{authToken}}


### Get pet search
GET {{host}}/pets/{{idFirstPetUser}}/search HTTP/1.1
content-type: application/json


### Get Pet for pet screen
GET {{host}}/pets/{{idFirstPetUser}} HTTP/1.1
content-type: application/json
Authorization: {{authToken}}


### Get pet contact
GET {{host}}/pets/{{idNewPet}}/contact HTTP/1.1
content-type: application/json
Authorization: {{authToken}}


### Get pets arrownd position
GET {{host}}/lostpets HTTP/1.1
    ?lat=-35.770438399999996&long=-58.48097550000001
content-type: application/json

### delete search from pet
DELETE {{host}}/users/{{idUserLoged}}/pets/{{idNewPet}}/search HTTP/1.1
content-type: application/json
Authorization: {{authToken}}


### Test image pets UPLOAD pet principal image and extras
POST  {{host}}/users/{{idUserLoged}}/pets/{{idFirstPetUser}}/pics
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: {{authToken}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

principal
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="principal"; filename="cute-dog.jpeg"
Content-Type: image/jpeg

< ./cute-dog.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="pics"; filename="cute-dog.jpeg"
Content-Type: image/jpeg

< ./cute-dog.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="pics"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### remove pics from pet with image name
DELETE   {{host}}/users/{{idUserLoged}}/pets/5d87b66cf8efcf0d4497ad9d/pics/principal1569179059043
Authorization: {{authToken}}


### remove pet 
DELETE   {{host}}/users/{{idUserLoged}}/pets/{{idFirstPetUser}}
Authorization: {{authToken}}

### obtain pic , deprecated?
get  {{host}}/users/{{idUserLoged}}/pets/5d87b66cf8efcf0d4497ad9d/pics/principal1569179059043
Authorization: {{authToken}}

# ###
# GET http://{{host}}/pets/{{idNewPet}}/principalPic

### 
get {{host}}/searchs/5d89488ebffed6294249ebb9/pic